### ISSUE TITLE
Make KiCad the latest 8.0 version in the dockerfile

### ISSUE THREAD

**Issue by gilleshenrard** [sparkengineering/kicad-action#2]
In Dockerfile, the KiCad version is specified as 8.0.2, forcing KiCad to that specific version.
Dockerhub allows kicad/kicad to be set at the latest 8.0 version by simply specifying "8.0".

Would it be possible to change the version number, as KiCad is now at version 8.0.4?

**Comment by leonrinkel** [comment]
Originally I wanted to allow pinning a specific version in the job configuration, however I haven't found an easy way of doing it. Using the major 8.0 release seems like a good compromise. Will do it, thanks!

**Comment by gilleshenrard** [comment]
Closing because I've created a pull request for this
